In [1]:
import numpy as np
import pandas as pd

### Data reading

In [2]:
movies = pd.read_csv("tmdb_5000_movies.csv")
credits = pd.read_csv("tmdb_5000_credits.csv")

In [3]:
movies.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800

In [4]:
credits.head(1)

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [5]:
movies.shape

(4803, 20)

In [6]:
credits.shape

(4803, 4)

In [7]:
movies = movies.merge(credits, on="title")

In [8]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4809 entries, 0 to 4808
Data columns (total 23 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4809 non-null   int64
 1   genres                4809 non-null   object
 2   homepage              1713 non-null   object
 3   id                    4809 non-null   int64
 4   keywords              4809 non-null   object
 5   original_language     4809 non-null   object
 6   original_title        4809 non-null   object
 7   overview              4806 non-null   object
 8   popularity            4809 non-null   float64
 9   production_companies  4809 non-null   object
 10  production_countries  4809 non-null   object
 11  release_date          4808 non-null   object
 12  revenue               4809 non-null   int64
 13  runtime               4807 non-null   float64
 14  spoken_languages      4809 non-null   object
 15  status                4809 non-null   object
 16  tagline               3965 non-null   object
 17  title                 4809 non-null   object
 18  vote_average          4809 non-null   float64
 19  vote_count            4809 non-null   int64
 20  movie_id              4809 non-null   int64
 21  cast                  4809 non-null   object
 22  crew                  4809 non-null   object
dtypes: float64(3), int64(5), object(15)
memory usage: 864.2+ KB

### Feature selection

In [9]:
selected_columns = ["movie_id","genres","keywords","title","overview","cast","crew"]
movies = movies[selected_columns]

In [10]:
movies.head()

,movie_id,genres,keywords,title,overview,cast,crew
0,19995,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

### Data cleaning

In [11]:
movies.isnull().sum()

movie_id    0
genres      0
keywords    0
title       0
overview    3
cast        0
crew        0
dtype: int64

In [12]:
movies.dropna(inplace = True)

In [13]:
movies.isnull().sum()

movie_id    0
genres      0
keywords    0
title       0
overview    0
cast        0
crew        0
dtype: int64

In [14]:
movies.duplicated().sum()

0

### Data transformation

In [15]:
movies.iloc[0]['genres']

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [16]:
import ast

def extract(row):
    try:
        # Convert string representation to an actual list and
        # Extract genre names 
        genre_names = [genre['name'] for genre in ast.literal_eval(row)]
        return genre_names
    except (ValueError, TypeError, KeyError):
        # Handle exceptions if the data is not in the expected format
        return []

In [17]:
movies['genres'] = movies['genres'].apply(extract)

In [18]:
movies.head()

,movie_id,genres,keywords,title,overview,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",Spectre,A cryptic message from Bond’s past sends him o...,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",John Carter,"John Carter is a war-weary, former military ca...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [19]:
movies['keywords'] = movies['keywords'].apply(extract)

In [20]:
def extract_cast(row):
    try:
        # Convert string representation to an actual list and
        # Extract genre names 
        genre_names = [genre['name'] for index, genre in enumerate(ast.literal_eval(row), 1) if index <= 3 ]
        return genre_names
    except (ValueError, TypeError, KeyError):
        # Handle exceptions if the data is not in the expected format
        return []

In [21]:
cast = movies.iloc[1].cast

In [22]:
cast

'[{"cast_id": 4, "character": "Captain Jack Sparrow", "credit_id": "52fe4232c3a36847f800b50d", "gender": 2, "id": 85, "name": "Johnny Depp", "order": 0}, {"cast_id": 5, "character": "Will Turner", "credit_id": "52fe4232c3a36847f800b511", "gender": 2, "id": 114, "name": "Orlando Bloom", "order": 1}, {"cast_id": 6, "character": "Elizabeth Swann", "credit_id": "52fe4232c3a36847f800b515", "gender": 1, "id": 116, "name": "Keira Knightley", "order": 2}, {"cast_id": 12, "character": "William \\"Bootstrap Bill\\" Turner", "credit_id": "52fe4232c3a36847f800b52d", "gender": 2, "id": 1640, "name": "Stellan Skarsg\\u00e5rd", "order": 3}, {"cast_id": 10, "character": "Captain Sao Feng", "credit_id": "52fe4232c3a36847f800b525", "gender": 2, "id": 1619, "name": "Chow Yun-fat", "order": 4}, {"cast_id": 9, "character": "Captain Davy Jones", "credit_id": "52fe4232c3a36847f800b521", "gender": 2, "id": 2440, "name": "Bill Nighy", "order": 5}, {"cast_id": 7, "character": "Captain Hector Barbossa", "credit_id": "52fe4232c3a36847f800b519", "gender": 2, "id": 118, "name": "Geoffrey Rush", "order": 6}, {"cast_id": 14, "character": "Admiral James Norrington", "credit_id": "52fe4232c3a36847f800b535", "gender": 2, "id": 1709, "name": "Jack Davenport", "order": 7}, {"cast_id": 13, "character": "Joshamee Gibbs", "credit_id": "52fe4232c3a36847f800b531", "gender": 2, "id": 2449, "name": "Kevin McNally", "order": 8}, {"cast_id": 11, "character": "Lord Cutler Beckett", "credit_id": "52fe4232c3a36847f800b529", "gender": 2, "id": 2441, "name": "Tom Hollander", "order": 9}, {"cast_id": 19, "character": "Tia Dalma", "credit_id": "52fe4232c3a36847f800b549", "gender": 1, "id": 2038, "name": "Naomie Harris", "order": 10}, {"cast_id": 8, "character": "Governor Weatherby Swann", "credit_id": "52fe4232c3a36847f800b51d", "gender": 2, "id": 378, "name": "Jonathan Pryce", "order": 11}, {"cast_id": 37, "character": "Captain Teague Sparrow", "credit_id": "52fe4232c3a36847f800b5b3", "gender": 2, "id": 1430, "name": "Keith Richards", "order": 12}, {"cast_id": 16, "character": "Pintel", "credit_id": "52fe4232c3a36847f800b53d", "gender": 2, "id": 1710, "name": "Lee Arenberg", "order": 13}, {"cast_id": 15, "character": "Ragetti", "credit_id": "52fe4232c3a36847f800b539", "gender": 2, "id": 1711, "name": "Mackenzie Crook", "order": 14}, {"cast_id": 18, "character": "Lieutenant Theodore Groves", "credit_id": "52fe4232c3a36847f800b545", "gender": 2, "id": 4031, "name": "Greg Ellis", "order": 15}, {"cast_id": 55, "character": "Cotton", "credit_id": "57e28d2ec3a3681a01005b5c", "gender": 2, "id": 1715, "name": "David Bailie", "order": 16}, {"cast_id": 17, "character": "Marty", "credit_id": "52fe4232c3a36847f800b541", "gender": 2, "id": 4030, "name": "Martin Klebba", "order": 17}, {"cast_id": 57, "character": "Ian Mercer", "credit_id": "57e28d78c3a36808b900bf4f", "gender": 0, "id": 939, "name": "David Schofield", "order": 18}, {"cast_id": 62, "character": "Scarlett", "credit_id": "57e28ec5c3a3681a50005855", "gender": 1, "id": 2450, "name": "Lauren Maher", "order": 19}, {"cast_id": 63, "character": "Giselle", "credit_id": "57e28ed692514123f5005635", "gender": 1, "id": 2452, "name": "Vanessa Branch", "order": 20}, {"cast_id": 60, "character": "Mullroy", "credit_id": "57e28db2c3a3681a01005bc7", "gender": 2, "id": 1714, "name": "Angus Barnett", "order": 21}, {"cast_id": 59, "character": "Murtogg", "credit_id": "57e28da192514118f7006008", "gender": 0, "id": 1713, "name": "Giles New", "order": 22}, {"cast_id": 58, "character": "Tai Huang", "credit_id": "57e28d8ec3a3681a01005bab", "gender": 2, "id": 22075, "name": "Reggie Lee", "order": 23}, {"cast_id": 64, "character": "Henry Turner", "credit_id": "57e29119925141151100a6cc", "gender": 2, "id": 61259, "name": "Dominic Scott Kay", "order": 24}, {"cast_id": 39, "character": "Mistress Ching", "credit_id": "52fe4232c3a36847f800b5bd", "gender": 1, "id": 33500, "name": "Takayo Fischer", "order": 25}, {"cast_id": 40, "character": "Lieutenant Greitzer", "credit_id": "52fe4232c3a36847f800b5c1", "gender": 2, "id": 1224149, "name": "David Meunier", "order": 26}, {"cast_id": 49, "character": "Hadras", "credit_id": "56d1871c92514174680010cf", "gender": 2, "id": 429401, "name": "Ho-Kwan Tse", "order": 27}, {"cast_id": 56, "character": "Clacker", "credit_id": "57e28d4b92514125710055cb", "gender": 0, "id": 1123, "name": "Andy Beckwith", "order": 28}, {"cast_id": 51, "character": "Penrod", "credit_id": "56ec8c14c3a3682260003c53", "gender": 2, "id": 1056117, "name": "Peter Donald Badalamenti II", "order": 29}, {"cast_id": 61, "character": "Cotton\'s Parrot (voice)", "credit_id": "57e28dcc9251412463005678", "gender": 2, "id": 21700, "name": "Christopher S. Capp", "order": 30}, {"cast_id": 65, "character": "Captain Teague", "credit_id": "58bc2a37c3a368663003740b", "gender": 2, "id": 1430, "name": "Keith Richards", "order": 31}, {"cast_id": 66, "character": "Captain Jocard", "credit_id": "58bc2a8e925141609e03a179", "gender": 2, "id": 2603, "name": "Hakeem Kae-Kazim", "order": 32}, {"cast_id": 67, "character": "Captain Ammand", "credit_id": "58e2a21ac3a36872af00f9c2", "gender": 0, "id": 70577, "name": "Ghassan Massoud", "order": 33}]'

In [23]:
cast = extract_cast(cast)

In [24]:
cast

['Johnny Depp', 'Orlando Bloom', 'Keira Knightley']

In [25]:
movies['cast'] = movies['cast'].apply(extract_cast)

In [26]:
movies.head()

,movie_id,genres,keywords,title,overview,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [27]:
def get_director(row):
    try:
        # Convert string representation to an actual list and
        # Extract genre names 
        director = [item['name'] for item in ast.literal_eval(row) if item.get("job") == "Director"]
        return director
    except (ValueError, TypeError, KeyError):
        # Handle exceptions if the data is not in the expected format
        return []

In [28]:
movies['crew'] = movies['crew'].apply(get_director)

In [29]:
movies.head()

,movie_id,genres,keywords,title,overview,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...",Avatar,"In the 22nd century, a paraplegic Marine is di...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",Spectre,A cryptic message from Bond’s past sends him o...,"[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,Following the death of District Attorney Harve...,"[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...",John Carter,"John Carter is a war-weary, former military ca...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [30]:
movies.overview[0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [31]:
movies['overview'] = movies['overview'].apply(lambda x:x.split())

In [32]:
movies.head()

,movie_id,genres,keywords,title,overview,cast,crew
0,19995,"[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,"[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...",Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[Daniel Craig, Christoph Waltz, Léa Seydoux]",[Sam Mendes]
3,49026,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,"[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [33]:
genre = movies.genres[0]
genre

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [34]:
''.join(genre).replace(' ', '').split(',')

['ActionAdventureFantasyScienceFiction']

In [35]:
genre = [item.replace(" ", "") for item in genre]

In [36]:
genre

['Action', 'Adventure', 'Fantasy', 'ScienceFiction']

In [37]:
def remove_whitespace(row):
    try:
        return [item.replace(" ", "") for item in row]
    except:
        return []

In [38]:
movies['genres'] = movies['genres'].apply(remove_whitespace)
movies['keywords'] = movies['keywords'].apply(remove_whitespace)
movies['cast'] = movies['cast'].apply(remove_whitespace)
movies['crew'] = movies['crew'].apply(remove_whitespace)

In [39]:
movies.head()

,movie_id,genres,keywords,title,overview,cast,crew
0,19995,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...",Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes]
3,49026,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [40]:
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [41]:
movies.head()

,movie_id,genres,keywords,title,overview,cast,crew,tags
0,19995,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...",Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],"[A, cryptic, message, from, Bond’s, past, send..."
3,49026,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [42]:
movies['tags'] = movies['tags'].apply(lambda x: " ".join(x))

In [43]:
movies.head()

,movie_id,genres,keywords,title,overview,cast,crew,tags
0,19995,"[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...",Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"In the 22nd century, a paraplegic Marine is di..."
1,285,"[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...",Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"Captain Barbossa, long believed to be dead, ha..."
2,206647,"[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...",Spectre,"[A, cryptic, message, from, Bond’s, past, send...","[DanielCraig, ChristophWaltz, LéaSeydoux]",[SamMendes],A cryptic message from Bond’s past sends him o...
3,49026,"[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...",The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],Following the death of District Attorney Harve...
4,49529,"[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...",John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"John Carter is a war-weary, former military ca..."

In [44]:
movies_df = movies[['movie_id','title','tags']]
movies_df

,movie_id,title,tags
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...
4,49529,John Carter,"John Carter is a war-weary, former military ca..."
...,...,...,...
4804,9367,El Mariachi,El Mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,A newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""Signed, Sealed, Delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,When ambitious New York attorney Sam is sent t...
4808,25975,My Date with Drew,Ever since the second grade when he first saw ...

In [45]:
type(movies_df.tags[0])

str

In [46]:
movies_df['tags'] = movies_df['tags'].apply(lambda x: x.lower())
movies_df.head()

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_17832\2987741751.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['tags'] = movies_df['tags'].apply(lambda x: x.lower())

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bond’s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

### Word stemming

In [47]:
! pip install nltk

Requirement already satisfied: nltk in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (3.8.1)
Requirement already satisfied: click in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from nltk) (8.1.3)
Requirement already satisfied: joblib in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from nltk) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from nltk) (2023.6.3)
Requirement already satisfied: tqdm in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from nltk) (4.65.0)
Requirement already satisfied: colorama in c:\users\lenovo\appdata\local\programs\python\python311\lib\site-packages (from click->nltk) (0.4.6)

In [48]:
from nltk.stem.porter import PorterStemmer

In [49]:
ps = PorterStemmer()

In [50]:
def stem(text):
    stemmed_text = [ps.stem(word) for word in text.split()]
    return " ".join(stemmed_text)

In [51]:
movies_df['tags'] = movies_df['tags'].apply(stem)

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_17832\2881018542.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  movies_df['tags'] = movies_df['tags'].apply(stem)

In [52]:
movies_df.tags[0]

'in the 22nd century, a parapleg marin is dispatch to the moon pandora on a uniqu mission, but becom torn between follow order and protect an alien civilization. action adventur fantasi sciencefict cultureclash futur spacewar spacecoloni societi spacetravel futurist romanc space alien tribe alienplanet cgi marin soldier battl loveaffair antiwar powerrel mindandsoul 3d samworthington zoesaldana sigourneyweav jamescameron'

### Model development

In [53]:
from sklearn.feature_extraction.text import CountVectorizer

In [54]:
cv = CountVectorizer(max_features=5000, stop_words='english')

In [55]:
vectors = cv.fit_transform(movies_df['tags']).toarray()

In [56]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [57]:
vectors.shape

(4806, 5000)

In [58]:
vectors[0]

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [59]:
list(cv.get_feature_names_out())

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '17th',
 '18',
 '18th',
 '18thcenturi',
 '19',
 '1910',
 '1920',
 '1930',
 '1940',
 '1944',
 '1950',
 '1950s',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1971',
 '1974',
 '1976',
 '1980',
 '1985',
 '1990',
 '1999',
 '19th',
 '19thcenturi',
 '20',
 '200',
 '2003',
 '2009',
 '20th',
 '21st',
 '23',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '70',
 '80',
 'aaron',
 'aaroneckhart',
 'abandon',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abus',
 'academ',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'acclaim',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'acquaint',
 'act',
 'action',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'ad',
 'adam',
 'adamsandl',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adult',
 'adultanim',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventure',
 'adventures',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agediffer',
 'agenc',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'aidanquinn',
 'ail',
 'aim',
 'air',
 'airplan',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcatraz',
 'alcohol',
 'alecbaldwin',
 'alex',
 'alexkendrick',
 'alfredhitchcock',
 'alfredmolina',
 'ali',
 'alic',
 'alice',
 'alien',
 'alieninvas',
 'alienlife',
 'alienplanet',
 'aliens',
 'alik',
 'aliv',
 'alive',
 'allen',
 'alli',
 'allianc',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alpha',
 'alreadi',
 'alter',
 'altern',
 'alway',
 'alyssa',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'amazon',
 'ambassador',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americancivilwar',
 'americanfootbal',
 'americanfootballplay',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amus',
 'amusementpark',
 'amy',
 'amyadam',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientrom',
 'ancientworld',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'android',
 'andy',
 'andygarcía',
 'angel',
 'angela',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'anger',
 'angle',
 'angri',
 'ani',
 'anim',
 'animalattack',
 'animalhorror',
 'animals',
 'anjelicahuston',
 'ann',
 'anna',
 'annafari',
 'annakendrick',
 'anne',
 'annehathaway',
 'annemoss',
 'annetteben',
 'anni',
 'annie',
 'anniversari',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthonymacki',
 'anthropomorph',
 'anti',
 'antic',
 'antihero',
 'antiqu',
 'antoinefuqua',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyps',
 'apocalypse',
 'apocalypt',
 'appar',
 'appear',
 'appl',
 'apple',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'archeolog',
 'archer',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'armor',
 'armsdeal',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'arrangedmarriag',
 'arrest',
 'arriv',
 'arrog',
 'art',
 'arthur',
 'artifact',
 'artifici',
 'artificialintellig',
 'artist',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'asia',
 'asian',
 'asid',
 'ask',
 'aspect',
 'aspir',
 'assassin',
 'assault',
 'assembl',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'atheist',
 'athlet',
 'atom',
 'atomicbomb',
 'attack',
 'attacks',
 'attempt',
 'attempttoescap',
 'attend',
 'attent',
 'attic',
 'attitud',
 'attorney',
 'attract',
 'auction',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'autism',
 'auto',
 'automobilerac',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awak',
 'awaken',
 'award',
 'away',
 'awkward',
 'awri',
 'awry',
 'ax',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'backpack',
 'bad',
 'bag',
 'bahama',
 'bail',
 'balanc',
 'ball',
 'ballet',
 'balloon',
 'ban',
 'band',
 'bandit',
 'bangkok',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bar',
 'barbrastreisand',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrylevinson',
 'barrysonnenfeld',
 'bas',
 'base',
 'basebal',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'bat',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'beam',
 'bear',
 'beard',
 'beast',
 'beat',
 'beauti',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becaus',
 'becki',
 'becom',
 'becominganadult',
 'bed',
 'bedroom',
 'beer',
 'befor',
 'befriend',
 'began',
 'begin',
 'begins',
 'behavior',
 'belief',
 'believ',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'bend',
 'beneath',
 'benefit',
 'benfost',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstil',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bestfriendsinlov',
 'bet',
 'beth',
 'betray',
 'bettemidl',
 'better',
 'betti',
 'beverli',
 'bibl',
 'bid',
 'big',
 'bigger',
 'biggest',
 'bike',
 'biker',
 'bikini',
 'billhad',
 'billi',
 'billionair',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billycrudup',
 'billycryst',
 'biographi',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blacksmith',
 'blade',
 'blame',
 'blend',
 'blind',
 'bliss',
 'blizzard',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'blow',
 'blue',
 'board',
 'boardingschool',
 'boat',
 'bob',
 'bobbi',
 'bobbyfarrelli',
 'bobhoskin',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'book',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'botch',
 'bound',
 'boundari',
 'bounti',
 'bountyhunt',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'boys',
 'bradleycoop',
 'bradpitt',
 'brain',
 'brand',
 'brandon',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breakup',
 'breast',
 'breath',
 'breed',
 'brendanfras',
 'brendangleeson',
 'brent',
 'brettratn',
 'brian',
 'briandepalma',
 'bride',
 'bridesmaid',
 'bridg',
 'brief',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'brink',
 'britain',
 'british',
 'britishsecretservic',
 'brittanymurphi',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'bronx',
 'brook',
 'brooklyn',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucegreenwood',
 'brucewilli',
 'brutal',
 'bryansing',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddy',
 'buddycomedi',
 'buddycop',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'bunch',
 'bunker',
 'bunni',
 'burglar',
 'buri',
 'burn',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butcher',
 'butler',
 'butt',
 'button',
 'buy',
 'buzz',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'calvin',
 'camcord',
 'came',
 'camera',
 'cameraman',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candi',
 'candid',
 'canin',
 'cannib',
 'canuxploit',
 'capabl',
 'caper',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'capture',
 'car',
 'caraccid',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'carefre',
 'caretak',
 'careymulligan',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrac',
 'carri',
 'carrie',
 'cartel',
 'carter',
 'cartoon',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'cataclysm',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherinedeneuv',
 'catherinekeen',
 'catherinezeta',
 'cathol',
 'catholic',
 'cattl',
 'caught',
 'caus',
 'cavalri',
 'cave',
 'cavemen',
 'celebr',
 'celebration',
 'cell',
 'cellphon',
 'cemeteri',
 'center',
 'centr',
 'central',
 'centuri',
 'centuries',
 'century',
 'ceo',
 'certain',
 'chad',
 'chain',
 'chainsaw',
 'challeng',
 'chamber',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chang',
 'change',
 'changed',
 'changes',
 'channingtatum',
 'chao',
 'chaos',
 'chaotic',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charli',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charm',
 'chart',
 'chase',
 'chauffeur',
 'chazzpalminteri',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chemic',
 'cher',
 'chevychas',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhero',
 'childhood',
 'childprodigi',
 'children',
 'chill',
 'chimp',
 'china',
 'chines',
 'chip',
 'chipmunk',
 'chiwetelejiofor',
 'chloe',
 'chloëgracemoretz',
 'chloësevigni',
 'chocol',
 'choic',
 'choice',
 'choos',
 'chosen',
 'chowyun',
 'chri',
 'chriscolumbu',
 'chriscoop',
 'chrisevan',
 'chrishemsworth',
 'chrisklein',
 'chrispin',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christianslat',
 'christin',
 'christinaappleg',
 'christinaricci',
 'christma',
 'christmas',
 'christmasparti',
 'christmastre',
 'christoph',
 'christopherlambert',
 'christopherlloyd',
 'christophernolan',
 'christopherplumm',
 'christopherwalken',
 'christophwaltz',
 'chrisweitz',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'ciaránhind',
 'cigarettesmok',
 'cillianmurphi',
 'cinema',
 'circl',
 'circu',
 'circuit',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civilian',
 'civilwar',
 'claim',
 'clair',
 'clairedan',
 'claireforlani',
 'clan',
 'clark',
 'clash',
 'class',
 'classdiffer',
 'classic',
 'classmat',
 'classroom',
 'claudevandamm',
 'clay',
 'clean',
 'clear',
 'clerk',
 'clever',
 'client',
 'clients',
 'cliff',
 'climat',
 'climb',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'close',
 'closer',
 'cloud',
 'clown',
 'club',
 'clue',
 'clueless',
 'clutch',
 'coach',
 'coast',
 'cocain',
 'code',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrel',
 'colinfirth',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'college',
 'collid',
 'collis',
 'colombia',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'coma',
 'combat',
 'combin',
 'come',
 'comeback',
 'comed',
 'comedi',
 'comedian',
 'comedy',
 'comet',
 'comfort',
 'comic',
 'coming',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commerci',
 'commiss',
 'commit',
 'common',
 'commun',
 'communist',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'compuls',
 'comput',
 'computerviru',
 'conan',
 'concern',
 'concert',
 'concoct',
 'condit',
 'condition',
 'conduct',
 'confeder',
 'confess',
 'confid',
 'confin',
 'conflict',
 'confront',
 'confus',
 'congress',
 'conman',
 'connect',
 'connecticut',
 'connel',
 'connor',
 'conquer',
 'consequ',
 'consequences',
 'conserv',
 'consid',
 'conspir',
 'conspiraci',
 'conspiracy',
 'constant',
 'constantli',
 'construct',
 'consum',
 'contact',
 'contain',
 'contemporari',
 'contend',
 'content',
 'contest',
 'continu',
 'contract',
 'contractor',
 'control',
 'controversi',
 'convent',
 'converg',
 'convers',
 'convict',
 'convinc',
 'cook',
 'cool',
 'cooper',
 'cop',
 'cope',
 ...]

In [60]:
from sklearn.metrics.pairwise import cosine_similarity

In [61]:
similarity = cosine_similarity(vectors)

In [62]:
similarity[0]

array([1.        , 0.08346223, 0.0860309 , ..., 0.04499213, 0.        ,
       0.        ])

In [63]:
similarity.shape

(4806, 4806)

In [64]:
movies_df[movies_df['title'] == "Batman"].index[0]

1360

In [65]:
sorted(list(enumerate(similarity[0])), reverse = True)

[(4805, 0.0),
 (4804, 0.0),
 (4803, 0.04499212706658476),
 (4802, 0.046829290579084706),
 (4801, 0.019252140716412975),
 (4800, 0.0),
 (4799, 0.052631578947368425),
 (4798, 0.04223886030955117),
 (4797, 0.0),
 (4796, 0.0),
 (4795, 0.0),
 (4794, 0.0),
 (4793, 0.05407380704358751),
 (4792, 0.0),
 (4791, 0.0),
 (4790, 0.0582716546748065),
 (4789, 0.060833032924035954),
 (4788, 0.0),
 (4787, 0.019117977822546817),
 (4786, 0.0),
 (4785, 0.019672236884115842),
 (4784, 0.043355498476206004),
 (4783, 0.0),
 (4782, 0.025649458802128853),
 (4781, 0.05923488777590923),
 (4780, 0.0),
 (4779, 0.0),
 (4778, 0.0),
 (4777, 0.10814761408717502),
 (4776, 0.0),
 (4775, 0.05647824947249051),
 (4774, 0.0),
 (4773, 0.029617443887954616),
 (4772, 0.023918243661746996),
 (4771, 0.039344473768231684),
 (4770, 0.0),
 (4769, 0.0),
 (4768, 0.0),
 (4767, 0.03627381250550058),
 (4766, 0.017195436249022724),
 (4765, 0.0),
 (4764, 0.0),
 (4763, 0.0),
 (4762, 0.0),
 (4761, 0.02742042485535409),
 (4760, 0.025334729596907),
 (4759, 0.019389168358237032),
 (4758, 0.0),
 (4757, 0.046829290579084706),
 (4756, 0.0),
 (4755, 0.026315789473684213),
 (4754, 0.08603090020146065),
 (4753, 0.0),
 (4752, 0.029617443887954616),
 (4751, 0.021119430154775586),
 (4750, 0.0),
 (4749, 0.0),
 (4748, 0.01981850088223545),
 (4747, 0.0),
 (4746, 0.0),
 (4745, 0.0),
 (4744, 0.03065696697424829),
 (4743, 0.014627012952620635),
 (4742, 0.040555355282690636),
 (4741, 0.0),
 (4740, 0.0),
 (4739, 0.025649458802128853),
 (4738, 0.0),
 (4737, 0.0837707816583391),
 (4736, 0.0),
 (4735, 0.0),
 (4734, 0.024115646544478436),
 (4733, 0.0),
 (4732, 0.0),
 (4731, 0.02782074420373286),
 (4730, 0.02294157338705618),
 (4729, 0.0),
 (4728, 0.0),
 (4727, 0.0533380747062665),
 (4726, 0.0),
 (4725, 0.0),
 (4724, 0.0),
 (4723, 0.0),
 (4722, 0.04120428217151646),
 (4721, 0.0),
 (4720, 0.028239124736245257),
 (4719, 0.0),
 (4718, 0.040555355282690636),
 (4717, 0.0),
 (4716, 0.0),
 (4715, 0.0),
 (4714, 0.0),
 (4713, 0.023174488732966077),
 (4712, 0.02271554252121273),
 (4711, 0.056573571480353566),
 (4710, 0.0),
 (4709, 0.0),
 (4708, 0.0),
 (4707, 0.025649458802128853),
 (4706, 0.011302501972710611),
 (4705, 0.0),
 (4704, 0.06362847629757779),
 (4703, 0.03382550457458692),
 (4702, 0.0),
 (4701, 0.0),
 (4700, 0.03244428422615251),
 (4699, 0.05564148840746572),
 (4698, 0.0),
 (4697, 0.0),
 (4696, 0.014567913668701625),
 (4695, 0.04024218182927669),
 (4694, 0.022075539284417398),
 (4693, 0.0602475233128778),
 (4692, 0.0),
 (4691, 0.052631578947368425),
 (4690, 0.023918243661746996),
 (4689, 0.0),
 (4688, 0.0),
 (4687, 0.0),
 (4686, 0.0),
 (4685, 0.0),
 (4684, 0.0),
 (4683, 0.0),
 (4682, 0.0),
 (4681, 0.0),
 (4680, 0.05923488777590923),
 (4679, 0.04499212706658476),
 (4678, 0.0),
 (4677, 0.0),
 (4676, 0.0),
 (4675, 0.027036903521793755),
 (4674, 0.02249606353329238),
 (4673, 0.11846977555181847),
 (4672, 0.04588314677411236),
 (4671, 0.028239124736245257),
 (4670, 0.03673591791853225),
 (4669, 0.028676966733820218),
 (4668, 0.0),
 (4667, 0.02742042485535409),
 (4666, 0.03181423814878889),
 (4665, 0.0),
 (4664, 0.06131393394849658),
 (4663, 0.0),
 (4662, 0.0207703246198632),
 (4661, 0.03181423814878889),
 (4660, 0.0),
 (4659, 0.031219527052723135),
 (4658, 0.0),
 (4657, 0.08111071056538127),
 (4656, 0.019389168358237032),
 (4655, 0.039344473768231684),
 (4654, 0.08111071056538127),
 (4653, 0.0),
 (4652, 0.06131393394849658),
 (4651, 0.040555355282690636),
 (4650, 0.0),
 (4649, 0.0),
 (4648, 0.018731716231633878),
 (4647, 0.021119430154775586),
 (4646, 0.039344473768231684),
 (4645, 0.0),
 (4644, 0.0),
 (4643, 0.04188539082916955),
 (4642, 0.0331133089266261),
 (4641, 0.08111071056538127),
 (4640, 0.07254762501100118),
 (4639, 0.0),
 (4638, 0.07079923254047887),
 (4637, 0.0),
 (4636, 0.057353933467640436),
 (4635, 0.039344473768231684),
 (4634, 0.025976216673306556),
 (4633, 0.02666903735313325),
 (4632, 0.03458572319330373),
 (4631, 0.0),
 (4630, 0.03419927840283847),
 (4629, 0.02913582733740325),
 (4628, 0.0),
 (4627, 0.04024218182927669),
 (4626, 0.08111071056538127),
 (4625, 0.0),
 (4624, 0.07694837640638656),
 (4623, 0.06488856845230502),
 (4622, 0.03458572319330373),
 (4621, 0.0),
 (4620, 0.025031308716087945),
 (4619, 0.04499212706658476),
 (4618, 0.029617443887954616),
 (4617, 0.0),
 (4616, 0.0),
 (4615, 0.0),
 (4614, 0.0),
 (4613, 0.0),
 (4612, 0.0),
 (4611, 0.03382550457458692),
 (4610, 0.0),
 (4609, 0.0),
 (4608, 0.0),
 (4607, 0.0415406492397264),
 (4606, 0.04188539082916955),
 (4605, 0.02666903735313325),
 (4604, 0.03382550457458692),
 (4603, 0.0),
 (4602, 0.05407380704358751),
 (4601, 0.0),
 (4600, 0.01981850088223545),
 (4599, 0.0),
 (4598, 0.0),
 (4597, 0.021486752129677003),
 (4596, 0.051298917604257706),
 (4595, 0.0),
 (4594, 0.0),
 (4593, 0.0),
 (4592, 0.0),
 (4591, 0.057353933467640436),
 (4590, 0.04783648732349399),
 (4589, 0.02666903735313325),
 (4588, 0.0),
 (4587, 0.08671099695241201),
 (4586, 0.0),
 (4585, 0.0),
 (4584, 0.0),
 (4583, 0.0),
 (4582, 0.052786150730834015),
 (4581, 0.0331133089266261),
 (4580, 0.03181423814878889),
 (4579, 0.029617443887954616),
 (4578, 0.0582716546748065),
 (4577, 0.0),
 (4576, 0.02294157338705618),
 (4575, 0.0),
 (4574, 0.017005425596285897),
 (4573, 0.03721614637823934),
 (4572, 0.0),
 (4571, 0.0),
 (4570, 0.0301237616564389),
 (4569, 0.028676966733820218),
 (4568, 0.08111071056538127),
 (4567, 0.0),
 (4566, 0.06131393394849658),
 (4565, 0.014686837386151168),
 (4564, 0.04188539082916955),
 (4563, 0.0),
 (4562, 0.0),
 (4561, 0.0),
 (4560, 0.08471737420873576),
 (4559, 0.03673591791853225),
 (4558, 0.076004188790721),
 (4557, 0.03823595564509363),
 (4556, 0.0),
 (4555, 0.040555355282690636),
 (4554, 0.03627381250550058),
 (4553, 0.024455799402225926),
 (4552, 0.04120428217151646),
 (4551, 0.0),
 (4550, 0.0),
 (4549, 0.023918243661746996),
 (4548, 0.0),
 (4547, 0.0),
 (4546, 0.0),
 (4545, 0.09558988911273408),
 (4544, 0.0),
 (4543, 0.02742042485535409),
 (4542, 0.07443229275647868),
 (4541, 0.0),
 (4540, 0.05407380704358751),
 (4539, 0.0),
 (4538, 0.13629325512727639),
 (4537, 0.0),
 (4536, 0.02913582733740325),
 (4535, 0.03382550457458692),
 (4534, 0.0),
 (4533, 0.051298917604257706),
 (4532, 0.033463724070512735),
 (4531, 0.0),
 (4530, 0.050669459193814),
 (4529, 0.01255307044856882),
 (4528, 0.04891159880445185),
 (4527, 0.0),
 (4526, 0.0),
 (4525, 0.04456565178215865),
 (4524, 0.023918243661746996),
 (4523, 0.0),
 (4522, 0.013809204416652687),
 (4521, 0.0),
 (4520, 0.0),
 (4519, 0.05006261743217589),
 (4518, 0.0),
 (4517, 0.0),
 (4516, 0.08671099695241201),
 (4515, 0.0),
 (4514, 0.02913582733740325),
 (4513, 0.0),
 (4512, 0.050669459193814),
 (4511, 0.027036903521793755),
 (4510, 0.025649458802128853),
 (4509, 0.0),
 (4508, 0.0),
 (4507, 0.0),
 (4506, 0.07987230638308718),
 (4505, 0.029617443887954616),
 (4504, 0.0),
 (4503, 0.0),
 (4502, 0.09365858115816941),
 (4501, 0.0),
 (4500, 0.0),
 (4499, 0.0),
 (4498, 0.025031308716087945),
 (4497, 0.0),
 (4496, 0.0),
 (4495, 0.0),
 (4494, 0.0),
 (4493, 0.0),
 (4492, 0.08111071056538127),
 (4491, 0.0),
 (4490, 0.09933992677987831),
 (4489, 0.015682536711195138),
 (4488, 0.0),
 (4487, 0.021873931962990357),
 (4486, 0.03382550457458692),
 (4485, 0.029617443887954616),
 (4484, 0.020942695414584774),
 (4483, 0.07098727864204515),
 (4482, 0.03244428422615251),
 (4481, 0.0),
 (4480, 0.0),
 (4479, 0.0),
 (4478, 0.0),
 (4477, 0.03823595564509363),
 (4476, 0.0),
 (4475, 0.0),
 (4474, 0.03627381250550058),
 (4473, 0.07647191129018727),
 (4472, 0.09733285267845754),
 (4471, 0.03797316245786213),
 (4470, 0.0),
 (4469, 0.025649458802128853),
 (4468, 0.11128297681493143),
 (4467, 0.028676966733820218),
 (4466, 0.03905832834322535),
 (4465, 0.0),
 (4464, 0.0),
 (4463, 0.03627381250550058),
 (4462, 0.0),
 (4461, 0.0),
 (4460, 0.03721614637823934),
 (4459, 0.05195243334661311),
 (4458, 0.04891159880445185),
 (4457, 0.0),
 (4456, 0.0),
 (4455, 0.0),
 (4454, 0.0),
 (4453, 0.0415406492397264),
 (4452, 0.0),
 (4451, 0.04499212706658476),
 (4450, 0.025334729596907),
 (4449, 0.0),
 (4448, 0.04461243988090516),
 (4447, 0.0),
 (4446, 0.023662426214015053),
 (4445, 0.0),
 (4444, 0.0),
 (4443, 0.07254762501100116),
 (4442, 0.0),
 (4441, 0.0),
 (4440, 0.0),
 (4439, 0.0),
 (4438, 0.0),
 (4437, 0.0331133089266261),
 (4436, 0.0),
 (4435, 0.0),
 (4434, 0.03244428422615251),
 (4433, 0.03181423814878889),
 (4432, 0.0),
 (4431, 0.07254762501100116),
 (4430, 0.0),
 (4429, 0.05546053999849018),
 (4428, 0.0),
 (4427, 0.04456565178215865),
 (4426, 0.0),
 (4425, 0.0),
 (4424, 0.0),
 (4423, 0.0),
 (4422, 0.025031308716087945),
 (4421, 0.03382550457458692),
 (4420, 0.029617443887954616),
 (4419, 0.0),
 (4418, 0.0),
 (4417, 0.0),
 (4416, 0.0),
 (4415, 0.0),
 (4414, 0.03382550457458692),
 (4413, 0.023414645289542353),
 (4412, 0.07443229275647868),
 (4411, 0.0),
 (4410, 0.025649458802128853),
 (4409, 0.0),
 (4408, 0.0602475233128778),
 (4407, 0.0),
 (4406, 0.028239124736245257),
 (4405, 0.18731716231633883),
 (4404, 0.0),
 (4403, 0.09733285267845754),
 (4402, 0.0301237616564389),
 (4401, 0.024738534799764674),
 (4400, 0.039344473768231684),
 (4399, 0.04588314677411236),
 (4398, 0.02294157338705618),
 (4397, 0.021300716142115247),
 (4396, 0.0),
 (4395, 0.0),
 (4394, 0.0),
 (4393, 0.0),
 (4392, 0.06814662756363819),
 (4391, 0.0),
 (4390, 0.03823595564509363),
 (4389, 0.02782074420373286),
 (4388, 0.018024602347862503),
 (4387, 0.0),
 (4386, 0.0),
 (4385, 0.0),
 (4384, 0.043747863925980714),
 (4383, 0.03498557142706598),
 (4382, 0.03993615319154359),
 (4381, 0.0),
 (4380, 0.025334729596907),
 (4379, 0.0),
 (4378, 0.0),
 (4377, 0.05484084971070818),
 (4376, 0.0),
 (4375, 0.040555355282690636),
 (4374, 0.0),
 (4373, 0.0),
 (4372, 0.046829290579084706),
 (4371, 0.023662426214015053),
 (4370, 0.0),
 (4369, 0.0533380747062665),
 (4368, 0.03823595564509363),
 (4367, 0.0),
 (4366, 0.0),
 (4365, 0.043355498476206004),
 (4364, 0.0),
 (4363, 0.0),
 (4362, 0.04188539082916955),
 (4361, 0.0),
 (4360, 0.0),
 (4359, 0.021486752129677003),
 (4358, 0.05990422978731538),
 (4357, 0.06243905410544627),
 (4356, 0.0),
 (4355, 0.06362847629757779),
 (4354, 0.0),
 (4353, 0.08998425413316952),
 (4352, 0.0),
 (4351, 0.0662266178532522),
 (4350, 0.0),
 (4349, 0.02913582733740325),
 (4348, 0.13497638119975428),
 (4347, 0.0),
 (4346, 0.0),
 (4345, 0.0),
 (4344, 0.0),
 (4343, 0.08998425413316952),
 (4342, 0.0),
 (4341, 0.07792865001991967),
 (4340, 0.0),
 (4339, 0.05407380704358751),
 (4338, 0.0),
 (4337, 0.0),
 (4336, 0.17521916101261562),
 (4335, 0.022282825891079324),
 (4334, 0.0),
 (4333, 0.040555355282690636),
 (4332, 0.03627381250550058),
 (4331, 0.09365858115816941),
 (4330, 0.05735393346764045),
 (4329, 0.050669459193814),
 (4328, 0.0),
 (4327, 0.025976216673306556),
 (4326, 0.03721614637823934),
 (4325, 0.046348977465932154),
 (4324, 0.03065696697424829),
 (4323, 0.025976216673306556),
 (4322, 0.0),
 (4321, 0.0),
 (4320, 0.06131393394849658),
 (4319, 0.03166237934306518),
 (4318, 0.0),
 (4317, 0.02249606353329238),
 (4316, 0.07894736842105264),
 (4315, 0.0),
 (4314, 0.019117977822546817),
 (4313, 0.028239124736245257),
 (4312, 0.06362847629757779),
 (4311, 0.0),
 (4310, 0.038778336716474064),
 (4309, 0.0),
 (4308, 0.0),
 (4307, 0.0),
 (4306, 0.0),
 (4305, 0.039344473768231684),
 (4304, 0.0),
 (4303, 0.0),
 (4302, 0.0),
 (4301, 0.0),
 (4300, 0.040555355282690636),
 (4299, 0.024182541670333724),
 (4298, 0.0),
 (4297, 0.03181423814878889),
 (4296, 0.0),
 (4295, 0.0),
 (4294, 0.0),
 (4293, 0.057353933467640436),
 (4292, 0.0),
 (4291, 0.0),
 (4290, 0.06917144638660747),
 (4289, 0.0),
 (4288, 0.025976216673306556),
 (4287, 0.023174488732966077),
 (4286, 0.023414645289542353),
 (4285, 0.0),
 (4284, 0.024738534799764674),
 (4283, 0.027036903521793755),
 (4282, 0.03627381250550058),
 (4281, 0.051298917604257706),
 (4280, 0.023662426214015053),
 (4279, 0.07868894753646337),
 (4278, 0.0),
 (4277, 0.018857857160117855),
 (4276, 0.0),
 (4275, 0.0),
 (4274, 0.0),
 (4273, 0.0),
 (4272, 0.0),
 (4271, 0.06362847629757779),
 (4270, 0.05923488777590923),
 (4269, 0.0),
 (4268, 0.0),
 (4267, 0.0),
 (4266, 0.07694837640638656),
 (4265, 0.0207703246198632),
 (4264, 0.0),
 (4263, 0.04891159880445185),
 (4262, 0.025031308716087945),
 (4261, 0.024182541670333724),
 (4260, 0.0),
 (4259, 0.039344473768231684),
 (4258, 0.026315789473684213),
 (4257, 0.057353933467640436),
 (4256, 0.0),
 (4255, 0.0),
 (4254, 0.09733285267845754),
 (4253, 0.0),
 (4252, 0.0),
 (4251, 0.0),
 (4250, 0.012988108336653278),
 (4249, 0.0),
 (4248, 0.024455799402225926),
 (4247, 0.019968076595771794),
 (4246, 0.039344473768231684),
 (4245, 0.0),
 (4244, 0.05407380704358751),
 (4243, 0.0),
 (4242, 0.02925402590524127),
 (4241, 0.040555355282690636),
 (4240, 0.0),
 (4239, 0.0),
 (4238, 0.023174488732966077),
 (4237, 0.0),
 (4236, 0.05006261743217589),
 (4235, 0.042973504259354006),
 (4234, 0.04188539082916955),
 (4233, 0.016303866268150616),
 (4232, 0.05195243334661311),
 (4231, 0.0),
 (4230, 0.0),
 (4229, 0.0),
 (4228, 0.12824729401064427),
 (4227, 0.0),
 (4226, 0.03181423814878889),
 (4225, 0.022282825891079324),
 (4224, 0.0),
 (4223, 0.041278324068019595),
 (4222, 0.0),
 (4221, 0.0),
 (4220, 0.0),
 (4219, 0.0),
 (4218, 0.03065696697424829),
 (4217, 0.0),
 (4216, 0.027036903521793755),
 (4215, 0.02271554252121273),
 (4214, 0.06765100914917384),
 (4213, 0.024738534799764674),
 (4212, 0.023174488732966077),
 (4211, 0.05407380704358751),
 (4210, 0.0),
 (4209, 0.03065696697424829),
 (4208, 0.0),
 (4207, 0.027036903521793755),
 (4206, 0.0),
 (4205, 0.02043797798283219),
 (4204, 0.0331133089266261),
 (4203, 0.07509392614826384),
 (4202, 0.03065696697424829),
 (4201, 0.09544271444636668),
 (4200, 0.0331133089266261),
 (4199, 0.0),
 (4198, 0.0),
 (4197, 0.0),
 (4196, 0.09933992677987831),
 (4195, 0.0),
 (4194, 0.06131393394849658),
 (4193, 0.03382550457458692),
 (4192, 0.02249606353329238),
 (4191, 0.02913582733740325),
 (4190, 0.2029530274475215),
 (4189, 0.0),
 (4188, 0.0),
 (4187, 0.0),
 (4186, 0.0),
 (4185, 0.024455799402225926),
 (4184, 0.0),
 (4183, 0.0),
 (4182, 0.03244428422615251),
 (4181, 0.0),
 (4180, 0.0),
 (4179, 0.04120428217151646),
 (4178, 0.06952346619889824),
 (4177, 0.02271554252121273),
 (4176, 0.04087595596566438),
 (4175, 0.0),
 (4174, 0.023174488732966077),
 (4173, 0.0),
 (4172, 0.0),
 (4171, 0.0),
 (4170, 0.0),
 (4169, 0.0),
 (4168, 0.0),
 (4167, 0.04120428217151646),
 (4166, 0.024738534799764674),
 (4165, 0.0),
 (4164, 0.0602475233128778),
 (4163, 0.07647191129018727),
 (4162, 0.0),
 (4161, 0.021486752129677003),
 (4160, 0.0),
 (4159, 0.03382550457458692),
 (4158, 0.044151078568834795),
 (4157, 0.0),
 (4156, 0.0),
 (4155, 0.0),
 (4154, 0.026315789473684213),
 (4153, 0.0),
 (4152, 0.03993615319154359),
 (4151, 0.0),
 (4150, 0.0),
 (4149, 0.04204138910034079),
 (4148, 0.0),
 (4147, 0.0),
 (4146, 0.04891159880445185),
 (4145, 0.0),
 (4144, 0.03458572319330373),
 (4143, 0.0),
 (4142, 0.0),
 (4141, 0.02782074420373286),
 (4140, 0.0),
 (4139, 0.028676966733820218),
 (4138, 0.0),
 (4137, 0.040555355282690636),
 (4136, 0.04024218182927669),
 (4135, 0.03382550457458692),
 (4134, 0.0),
 (4133, 0.10619884881071831),
 (4132, 0.052631578947368425),
 (4131, 0.0),
 (4130, 0.03458572319330373),
 (4129, 0.03721614637823934),
 (4128, 0.03823595564509363),
 (4127, 0.014870813293635054),
 (4126, 0.0),
 (4125, 0.02666903735313325),
 (4124, 0.0),
 (4123, 0.05564148840746572),
 (4122, 0.025031308716087945),
 (4121, 0.06814662756363819),
 (4120, 0.0),
 (4119, 0.0),
 (4118, 0.05990422978731538),
 (4117, 0.0301237616564389),
 (4116, 0.0),
 (4115, 0.04543108504242546),
 (4114, 0.02878964680142297),
 (4113, 0.02666903735313325),
 (4112, 0.029617443887954616),
 (4111, 0.02913582733740325),
 (4110, 0.05923488777590923),
 (4109, 0.0),
 (4108, 0.02742042485535409),
 (4107, 0.027036903521793755),
 (4106, 0.0),
 (4105, 0.03065696697424829),
 (4104, 0.0),
 (4103, 0.02043797798283219),
 (4102, 0.0),
 (4101, 0.037463432463267755),
 (4100, 0.0),
 (4099, 0.0),
 (4098, 0.055824219567359015),
 (4097, 0.05923488777590923),
 (4096, 0.0),
 (4095, 0.10259783520851541),
 (4094, 0.0),
 (4093, 0.0),
 (4092, 0.03181423814878889),
 (4091, 0.0),
 (4090, 0.0),
 (4089, 0.0301237616564389),
 (4088, 0.0533380747062665),
 (4087, 0.0),
 (4086, 0.0),
 (4085, 0.04947706959952935),
 (4084, 0.0),
 (4083, 0.028676966733820218),
 (4082, 0.04543108504242546),
 (4081, 0.07175473098524099),
 (4080, 0.0),
 (4079, 0.0),
 (4078, 0.04783648732349399),
 (4077, 0.13157894736842107),
 (4076, 0.026315789473684213),
 (4075, 0.05990422978731538),
 (4074, 0.039344473768231684),
 (4073, 0.04188539082916955),
 (4072, 0.0),
 (4071, 0.0),
 (4070, 0.0331133089266261),
 (4069, 0.0),
 (4068, 0.0),
 (4067, 0.025649458802128853),
 (4066, 0.044151078568834795),
 (4065, 0.02294157338705618),
 (4064, 0.03721614637823934),
 (4063, 0.02666903735313325),
 (4062, 0.0),
 (4061, 0.023918243661746996),
 (4060, 0.04499212706658476),
 (4059, 0.0662266178532522),
 (4058, 0.0),
 (4057, 0.021873931962990357),
 (4056, 0.0),
 (4055, 0.0),
 (4054, 0.0),
 (4053, 0.05407380704358751),
 (4052, 0.0),
 (4051, 0.0),
 (4050, 0.043355498476206004),
 (4049, 0.0207703246198632),
 (4048, 0.0),
 (4047, 0.0),
 (4046, 0.2278389747471728),
 (4045, 0.025031308716087945),
 (4044, 0.0602475233128778),
 (4043, 0.076004188790721),
 (4042, 0.03721614637823934),
 (4041, 0.019968076595771794),
 (4040, 0.05923488777590923),
 (4039, 0.0),
 (4038, 0.0),
 (4037, 0.028676966733820218),
 (4036, 0.03181423814878889),
 (4035, 0.028239124736245257),
 (4034, 0.046829290579084706),
 (4033, 0.0),
 (4032, 0.0),
 (4031, 0.0),
 (4030, 0.0),
 (4029, 0.0),
 (4028, 0.03721614637823934),
 (4027, 0.03244428422615251),
 (4026, 0.01391037210186643),
 (4025, 0.0),
 (4024, 0.043355498476206004),
 (4023, 0.03539961627023944),
 (4022, 0.016643566632465155),
 (4021, 0.02913582733740325),
 (4020, 0.01981850088223545),
 (4019, 0.021300716142115247),
 (4018, 0.0),
 (4017, 0.0662266178532522),
 (4016, 0.09933992677987831),
 (4015, 0.020121090914638345),
 (4014, 0.0),
 (4013, 0.0),
 (4012, 0.0),
 (4011, 0.021677749238103002),
 (4010, 0.0415406492397264),
 (4009, 0.07443229275647868),
 (4008, 0.15737789507292674),
 (4007, 0.02742042485535409),
 (4006, 0.031219527052723135),
 (4005, 0.0),
 (4004, 0.06362847629757779),
 (4003, 0.0),
 (4002, 0.0),
 (4001, 0.019529164171612674),
 (4000, 0.03498557142706598),
 (3999, 0.0),
 (3998, 0.11803342130469505),
 (3997, 0.18074256993863339),
 (3996, 0.0),
 (3995, 0.04223886030955117),
 (3994, 0.03627381250550058),
 (3993, 0.0582716546748065),
 (3992, 0.0662266178532522),
 (3991, 0.01813690625275029),
 (3990, 0.04588314677411236),
 (3989, 0.024738534799764674),
 (3988, 0.02294157338705618),
 (3987, 0.0301237616564389),
 (3986, 0.04188539082916955),
 (3985, 0.029617443887954616),
 (3984, 0.0),
 (3983, 0.0),
 (3982, 0.0),
 (3981, 0.031219527052723135),
 (3980, 0.13530201829834768),
 (3979, 0.0),
 (3978, 0.0),
 (3977, 0.03181423814878889),
 (3976, 0.0837707816583391),
 (3975, 0.02742042485535409),
 (3974, 0.07254762501100116),
 (3973, 0.0),
 (3972, 0.0),
 (3971, 0.0),
 (3970, 0.03627381250550058),
 (3969, 0.03539961627023944),
 (3968, 0.0),
 (3967, 0.0),
 (3966, 0.031219527052723135),
 (3965, 0.0),
 (3964, 0.0),
 (3963, 0.0),
 (3962, 0.0),
 (3961, 0.019389168358237032),
 (3960, 0.03823595564509363),
 (3959, 0.01749278571353299),
 (3958, 0.0),
 (3957, 0.0),
 (3956, 0.0),
 (3955, 0.0),
 (3954, 0.02913582733740325),
 (3953, 0.03382550457458692),
 (3952, 0.10147651372376076),
 (3951, 0.028239124736245257),
 (3950, 0.0),
 (3949, 0.030254451040802585),
 (3948, 0.021300716142115247),
 (3947, 0.043355498476206004),
 (3946, 0.03797316245786213),
 (3945, 0.03582871819500093),
 (3944, 0.03181423814878889),
 (3943, 0.0),
 (3942, 0.0),
 (3941, 0.0),
 (3940, 0.0),
 (3939, 0.04188539082916955),
 (3938, 0.0),
 (3937, 0.0),
 (3936, 0.043355498476206004),
 (3935, 0.022075539284417398),
 (3934, 0.0),
 (3933, 0.0989541391990587),
 (3932, 0.024182541670333724),
 (3931, 0.0),
 (3930, 0.024455799402225926),
 (3929, 0.06362847629757779),

### Main function

In [66]:
def recommend(movie):
    movie_index = movies_df[movies_df['title'] == movie].index[0]
    distances = similarity[movie_index]
    movies_list = sorted(list(enumerate(distances)), reverse = True, key=lambda x:x[1])[1:6]
    
    for i in movies_list:
        print(movies_df.iloc[i[0]].title)

In [67]:
recommend("Batman")

Batman
Batman & Robin
Batman Begins
Batman Returns
The R.M.

In [68]:
import pickle

In [69]:
# pickle.dump(movies_df, open('movies_list.pkl', 'wb'))
pickle.dump(movies_df, open('movies_list.pkl', 'wb'),
            protocol=pickle.HIGHEST_PROTOCOL)


# pickle.dump(similarity, open('similarity.pkl', 'wb'))